config/routes.rb
Rails.application.routes.draw do
  resources :pets

  get 'pets/index'
  get 'pets/show'
  get 'pets/new'
  get 'pets/edit'
  get 'hello/index'
  root 'pets#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :description, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[ :id])
  end

  def new
    @pet = Pet.new
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])

    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated' }
      else
        format.turbo_stream
        format.html { render :edit }
      end
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end

  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
      else
        format.turbo_stream
        format.html { render :new }
      end
    end
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :age, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/hello/index.html.erb
<h1>Hello World on Rails!</h1>
<p>Find me in app/views/hello/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert <%= 'alert-info' if name == 'notice' %> <%= 'alert-danger' if name == 'alert' %>">
          <%= msg %>
        </div>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pets/_form_errors.html.erb
<% if pet.errors.any? %>
  <div id="form_errors" class="errors">
    <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being <%= action %>:</h2>
    <ul>
      <% pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/pets/create.turbo_stream.erb
<%= turbo_stream.update 'form_errors', partial: 'form_errors', locals: { pet: @pet, action: 'saved' } %>

app/views/pets/edit.html.erb
<h1>Edit Pet</h1>

<div id="form_update_errors">
   <!-- Errors will be displayed here -->
</div>

<%= form_with model: @pet, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%=  form.label :age %><br>
    <%= form.text_area :age %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description%>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/pets/index.html.erb
<table>
  <tr>
    <th colspan="5">My Pets</th>
  </tr>
  <% @pets.each do |p| %>
    <tr>
      <td><%= link_to p.name, pet_path(p) %></td>
      <td><%= link_to 'Edit', edit_pet_path(p) %></td>
      <td><%= link_to 'Remove', pet_path(p), data: { turbo_method: "delete", turbo_confirm: 'Are you sure?' } %></td>
    </tr>
  <% end%>
</table>

<br>

<%= link_to 'New pet', new_pet_path %><br>

app/views/pets/new.html.erb
<h1>New pet</h1>

<div id="form_errors">
   <!-- Errors will be displayed here -->
</div>

<%= form_with scope: :pet, url: pets_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :age %><br>
    <%= form.text_area :age %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/pets/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @pet.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pet.age %>
</p>

<p>
  <strong>Description</strong>
  <%= @pet.description %>
</p>

<%= link_to 'Edit', edit_pet_path %><br>
<%= link_to 'Remove', @pet, data: { turbo_method: "delete", turbo_confirm: 'Are you sure?' } %><br>
<%= link_to 'Home', pets_path %>

app/views/pets/update.turbo_stream.erb
<%= turbo_stream.update 'form_errors', partial: 'form_errors', locals: { pet: @pet, action: 'updated' } %>